import type { IExecuteFunctions, INode } from 'n8n-workflow';
import { describe, expect, it } from 'vitest';

import { buildMovieRequestBody } from '../nodes/Json2Video/actions/movie/movieRequestBody';

const node: INode = {
	id: 'a1',
	name: 'JSON2Video',
	type: 'n8n-nodes-json2video.json2Video',
	typeVersion: 1,
	position: [0, 0],
	parameters: {},
};

/** Minimal `IExecuteFunctions` stand-in: the builder only reads parameters. */
function fakeExecuteFunctions(parameters: Record<string, unknown>) {
	return {
		getNode: () => node,
		getNodeParameter: (name: string, _itemIndex: number, fallback?: unknown) =>
			name in parameters ? parameters[name] : fallback,
	} as unknown as IExecuteFunctions;
}

describe('buildMovieRequestBody — Template mode', () => {
	it('builds { template, variables } from the key/value fields', () => {
		const context = fakeExecuteFunctions({
			inputMode: 'template',
			templateId: 'LerKrmBfiqaIgBuacLWn',
			specifyVariables: 'keypair',
			variablesUi: {
				variable: [
					{ name: 'headline', value: 'Summer sale' },
					{ name: 'product_image', value: 'https://example.com/shoe.jpg' },
				],
			},
			additionalOptions: {},
		});

		expect(buildMovieRequestBody.call(context, 0)).toEqual({
			template: 'LerKrmBfiqaIgBuacLWn',
			variables: {
				headline: 'Summer sale',
				product_image: 'https://example.com/shoe.jpg',
			},
		});
	});

	it('accepts variables as JSON for numbers and nested values', () => {
		const context = fakeExecuteFunctions({
			inputMode: 'template',
			templateId: 'LerKrmBfiqaIgBuacLWn',
			specifyVariables: 'json',
			variablesJson: '{"price": 49.9, "tags": ["a","b"]}',
			additionalOptions: {},
		});

		expect(buildMovieRequestBody.call(context, 0)).toEqual({
			template: 'LerKrmBfiqaIgBuacLWn',
			variables: { price: 49.9, tags: ['a', 'b'] },
		});
	});

	it('expands the Webhook URL option into the nested exports shape', () => {
		const context = fakeExecuteFunctions({
			inputMode: 'template',
			templateId: 'LerKrmBfiqaIgBuacLWn',
			specifyVariables: 'keypair',
			variablesUi: {},
			additionalOptions: {
				resolution: 'instagram-story',
				webhookUrl: 'https://n8n.example.com/webhook/j2v-done',
			},
		});

		expect(buildMovieRequestBody.call(context, 0)).toEqual({
			template: 'LerKrmBfiqaIgBuacLWn',
			resolution: 'instagram-story',
			exports: [
				{
					destinations: [
						{
							type: 'webhook',
							endpoint: 'https://n8n.example.com/webhook/j2v-done',
							'content-type': 'application/json',
						},
					],
				},
			],
		});
	});

	it('fails with a NodeOperationError when no template was selected', () => {
		const context = fakeExecuteFunctions({
			inputMode: 'template',
			templateId: '',
			additionalOptions: {},
		});

		expect(() => buildMovieRequestBody.call(context, 0)).toThrowError(/No template selected/);
	});
});

describe('buildMovieRequestBody — Movie JSON mode', () => {
	it('sends the parsed document, with Additional Options overriding it', () => {
		const context = fakeExecuteFunctions({
			inputMode: 'json',
			movieJson: '{"resolution":"sd","scenes":[{"elements":[]}]}',
			additionalOptions: { resolution: 'full-hd', comment: 'Generated by n8n' },
		});

		expect(buildMovieRequestBody.call(context, 0)).toEqual({
			resolution: 'full-hd',
			scenes: [{ elements: [] }],
			comment: 'Generated by n8n',
		});
	});

	it('rejects malformed Movie JSON before any request is sent', () => {
		const context = fakeExecuteFunctions({
			inputMode: 'json',
			movieJson: '{"scenes": [}',
			additionalOptions: {},
		});

		expect(() => buildMovieRequestBody.call(context, 0)).toThrowError(
			/Movie JSON is not valid JSON/,
		);
	});
});
