import { describe, expect, it } from 'vitest';

import {
	applyMovieOptions,
	buildWebhookExports,
	isTerminalStatus,
	keyValuePairsToObject,
	parseExportsParameter,
	parseJsonObjectParameter,
	simplifyMovieResponse,
	validateProjectId,
} from '../nodes/Json2Video/helpers/movie';

describe('parseJsonObjectParameter (Movie JSON client-side validation)', () => {
	it('parses a valid Movie JSON document', () => {
		const movie = parseJsonObjectParameter(
			'{"resolution":"full-hd","scenes":[{"elements":[]}]}',
			'Movie JSON',
		);
		expect(movie).toEqual({ resolution: 'full-hd', scenes: [{ elements: [] }] });
	});

	it('accepts an object straight from an expression', () => {
		const movie = parseJsonObjectParameter({ resolution: 'hd' }, 'Movie JSON');
		expect(movie).toEqual({ resolution: 'hd' });
	});

	it('names the parameter and the parse position on malformed JSON', () => {
		expect(() => parseJsonObjectParameter('{"scenes": [}', 'Movie JSON')).toThrowError(
			/^Movie JSON is not valid JSON: /,
		);
	});

	it('rejects an empty editor', () => {
		expect(() => parseJsonObjectParameter('   ', 'Movie JSON')).toThrowError(
			'Movie JSON is empty. Provide a JSON object.',
		);
	});

	it('rejects JSON that is not an object', () => {
		expect(() => parseJsonObjectParameter('[1,2,3]', 'Movie JSON')).toThrowError(
			'Movie JSON must be a JSON object, but it is an array.',
		);
		expect(() => parseJsonObjectParameter('"hello"', 'Movie JSON')).toThrowError(
			'Movie JSON must be a JSON object, but it is a string.',
		);
	});
});

describe('buildWebhookExports (Appendix B / B3)', () => {
	it('expands a flat URL into the nested exports shape the API expects', () => {
		expect(buildWebhookExports('https://n8n.example.com/webhook/j2v-done')).toEqual([
			{
				destinations: [
					{
						type: 'webhook',
						endpoint: 'https://n8n.example.com/webhook/j2v-done',
						'content-type': 'application/json',
					},
				],
			},
		]);
	});

	it('keeps content-type as a full MIME string, not the short "json" form', () => {
		const [entry] = buildWebhookExports('https://example.com/hook');
		const destination = (entry.destinations as Array<Record<string, unknown>>)[0];
		expect(destination['content-type']).toBe('application/json');
	});
});

describe('keyValuePairsToObject', () => {
	it('flattens a fixedCollection into a plain object', () => {
		const value = {
			variable: [
				{ name: 'headline', value: 'Summer sale' },
				{ name: 'price', value: '49.9' },
			],
		};
		expect(keyValuePairsToObject(value, 'variable')).toEqual({
			headline: 'Summer sale',
			price: '49.9',
		});
	});

	it('ignores entries without a name and returns {} for empty input', () => {
		expect(keyValuePairsToObject({ variable: [{ name: '  ', value: 'x' }] }, 'variable')).toEqual({});
		expect(keyValuePairsToObject({}, 'variable')).toEqual({});
		expect(keyValuePairsToObject(undefined, 'variable')).toEqual({});
	});
});

describe('applyMovieOptions', () => {
	it('adds nothing when no option was set', () => {
		expect(applyMovieOptions({ template: 'LerKrmBfiqaIgBuacLWn' }, {})).toEqual({
			template: 'LerKrmBfiqaIgBuacLWn',
		});
	});

	it('maps the documented options onto their API property names', () => {
		const body = applyMovieOptions(
			{ template: 'LerKrmBfiqaIgBuacLWn' },
			{
				resolution: 'instagram-story',
				quality: 'high',
				fps: 30,
				cache: false,
				id: 'my-movie-1',
				comment: 'Generated by n8n',
				clientData: { data: [{ name: 'order_id', value: 'ord_42' }] },
				webhookUrl: 'https://n8n.example.com/webhook/j2v-done',
			},
		);

		expect(body).toEqual({
			template: 'LerKrmBfiqaIgBuacLWn',
			resolution: 'instagram-story',
			quality: 'high',
			fps: 30,
			cache: false,
			id: 'my-movie-1',
			comment: 'Generated by n8n',
			'client-data': { order_id: 'ord_42' },
			exports: [
				{
					destinations: [
						{
							type: 'webhook',
							endpoint: 'https://n8n.example.com/webhook/j2v-done',
							'content-type': 'application/json',
						},
					],
				},
			],
		});
	});

	it('only sends width and height for a custom resolution', () => {
		expect(applyMovieOptions({}, { resolution: 'custom', width: 1080, height: 1920 })).toEqual({
			resolution: 'custom',
			width: 1080,
			height: 1920,
		});
		expect(applyMovieOptions({}, { resolution: 'full-hd', width: 1080, height: 1920 })).toEqual({
			resolution: 'full-hd',
		});
	});

	it('overrides top-level properties of a Movie JSON document', () => {
		const body = applyMovieOptions(
			{ resolution: 'sd', quality: 'low', scenes: [] },
			{ resolution: 'full-hd', quality: 'high' },
		);
		expect(body).toEqual({ resolution: 'full-hd', quality: 'high', scenes: [] });
	});

	it('lets the advanced Exports field win over Webhook URL', () => {
		const body = applyMovieOptions(
			{},
			{
				webhookUrl: 'https://n8n.example.com/webhook/j2v-done',
				exports: '[{"destinations":[{"type":"ftp","host":"ftp.example.com"}]}]',
			},
		);
		expect(body.exports).toEqual([{ destinations: [{ type: 'ftp', host: 'ftp.example.com' }] }]);
	});

	it('surfaces a broken Exports JSON before any request is made', () => {
		expect(() => applyMovieOptions({}, { exports: '[{' })).toThrowError(
			/^Exports \(JSON\) is not valid JSON: /,
		);
	});
});

describe('parseExportsParameter', () => {
	it('wraps a single export object into an array', () => {
		expect(parseExportsParameter('{"destinations":[]}')).toEqual([{ destinations: [] }]);
	});

	it('returns an empty array for an empty value', () => {
		expect(parseExportsParameter('')).toEqual([]);
	});
});

describe('validateProjectId', () => {
	it('accepts a 16-character ID and trims it', () => {
		expect(validateProjectId(' JkGxEoPRF9EgRb32 ')).toBe('JkGxEoPRF9EgRb32');
	});

	it('rejects the wrong length with the length in the message', () => {
		expect(() => validateProjectId('too-short')).toThrowError(
			'Project ID must be a 16-character string. Received "too-short" (length: 9).',
		);
	});

	it('rejects an empty value', () => {
		expect(() => validateProjectId('')).toThrowError(/^Project ID is required/);
	});
});

describe('simplifyMovieResponse', () => {
	it('unwraps the movie object and keeps the remaining quota', () => {
		const simplified = simplifyMovieResponse({
			success: true,
			movie: { status: 'done', url: 'https://assets.json2video.com/a.mp4' },
			remaining_quota: { time: 1807 },
		});
		expect(simplified).toEqual({
			status: 'done',
			url: 'https://assets.json2video.com/a.mp4',
			remaining_quota: { time: 1807 },
		});
	});

	it('returns the raw response when there is no movie object', () => {
		expect(simplifyMovieResponse({ success: true })).toEqual({ success: true });
	});
});

describe('isTerminalStatus', () => {
	it('treats done, error and timeout as terminal', () => {
		expect(isTerminalStatus('done')).toBe(true);
		expect(isTerminalStatus('error')).toBe(true);
		expect(isTerminalStatus('timeout')).toBe(true);
	});

	it('keeps waiting on pending and running', () => {
		expect(isTerminalStatus('pending')).toBe(false);
		expect(isTerminalStatus('running')).toBe(false);
		expect(isTerminalStatus(undefined)).toBe(false);
	});
});
